name=WS2812Capture
version=1.0.0
author=Paul Stoffregen
maintainer=Paul Stoffregen
sentence=Capture and Analyze Timing of WS2812 LED Data
paragraph=WS2812Capture is a Teensy 4.x library which can capture and analyze WS2812 LED data. Its primary purpose is to verify the correctness of timing used by other libraries which transmit data to WS2812 addressable LEDs.
category=Display
url=https://github.com/PaulStoffregen/WS2812Capture
architectures=*

